### ISSUE TITLE
씬마다 보여줄 컨트롤러를 정해야 한다.

### ISSUE THREAD

**Issue by Invidam** [LazoYoung/EcoDiver#102]

**Comment by WooTak123** [comment]
- 타이틀 씬(이전의 기존 컨트롤러 모델)
- 프롤로그 씬(잠수복 없이 손만, 새로 만들어야함 금방함)
- 퀘스트 1,2,3 (디바이스 부착된 모델, 변경없음)

프리팹 계층에 새로 만든 손 프리팹 만들고 컨트롤러 모델도 프리팹 생성
툴 목록에 현재 4개가 있으며, 추가적으로 2개를 만들어서 새로 만든 프리팹 2개를 가리키도록 설정
Game Systems > Equipment 인스펙터에서 Default Tool 항목으로 설정

**Comment by Invidam** [comment]
해결되야 #99 진행이 될 듯

**Comment by LazoYoung** [comment]
@Invidam 프롤로그 씬만 처리하면 끝나고 현재 진행중이라고 합니다

**Comment by Invidam** [comment]
@WooTak123 해결 된거면 이슈 닫아줘
