### ISSUE TITLE
타이틀 메뉴 `:hover` 이벤트가 발생하지 않는다. -- 박찬영

### ISSUE THREAD

**Issue by Invidam** [LazoYoung/EcoDiver#104]

**Comment by WooTak123** [comment]
PC 환경 상호작용은 우선순위를 뒤로 미루더라도, Hover 기능은 해결해야할 것 같습니다. UI 관련해서 해결해 주실 수 있나요? @LazoYoung @Invidam

**Comment by LazoYoung** [comment]
@Invidam 이거 작업 아직 안들어갔다면 제가할게요
