### ISSUE TITLE
타이틀 씬 배경음 (기존 Background 대신 바다 소리로 변경, 기존 것은 NRE 에러가 종종 뜸)

### ISSUE THREAD

**Issue by Invidam** [LazoYoung/EcoDiver#106]

**Comment by Invidam** [comment]
해결 어떻게 된거야? 나 코드 안바꾼 게 없는데

**Comment by Invidam** [comment]
@WooTak123 진행사항 있는거야 이거?

**Comment by WooTak123** [comment]
@Invidam 사운드 재생은 그냥 기존의 Water sound manager로만 사용하면 문제 없을 것 같아서 해결한걸로 쳤어.
바닷소리+갈매기소리 재생은 문제 없이 되는데 여기에 중복되게 배경음악(잔잔한 가사없는 노래 같은거)도 동시에 재생시킬거면 스크립트 따로 추가하거나 기존 Water sound manager 스크립트 수정하면 좋을 듯
