### ISSUE TITLE
씬 전환 이슈

### ISSUE THREAD

**Issue by WooTak123** [LazoYoung/EcoDiver#111]
![image](https://github.com/LazoYoung/EcoDiver/assets/129940293/17569d3d-4f8f-4fde-8460-7fb23c33613e)

타이틀 씬에서 B키 또는 Start 선택하여 씬 전환시 전환이 되지 않음

**Comment by LazoYoung** [comment]
merge하다가 씬이 중복되서 본인 실수였고 해결했다고 합니다
