### ISSUE TITLE
퀘스트1 퀘스트 영역이 안보임

### ISSUE THREAD

**Issue by Invidam** [LazoYoung/EcoDiver#118]
퀘스트 영역, 퀘스트 설정이 어느샌가 빠진 것 확인함.

깃헙 봐가며 복구하겠음

추가로 화살표 on/off 설정도 다시해야 할 듯.

**Comment by WooTak123** [comment]
@Invidam 화살표 토글 기능이 평상시에는 표시되고 퀘스트 영역 안에 들어가면 꺼지게 구현하는걸로 알고 있는데 맞나요?
