### ISSUE TITLE
`OceanRenderer` 을 이용하여 수심, 잠수 여부를 판단하도록 수정한다.

### ISSUE THREAD

**Issue by Invidam** [LazoYoung/EcoDiver#46]
`OceanRenderer.Instance.ViewerHeightAboveWater`, `OceanSampleHeightEvents`를 활용할 것.

일단 관련 내용은 TODO 주석으로 메모해놓음.

**Comment by LazoYoung** [comment]
완료되었다면 close 부탁합니다
