### ISSUE TITLE
게임 성능을 최적화한다

### ISSUE THREAD

**Issue by LazoYoung** [LazoYoung/EcoDiver#53]
- [x] Level of Detail 기법 적용
- [x] 수많은 오브젝트의 LOD 적용을 자동화하는 스크립트
- [x] Culling Group을 사용하여 시야에 들어오는 오브젝트만 렌더링하는 스크립트
- [x] ~~렌더 파이프라인 최적화 여부 탐색~~

VR 평균 60fps 목표치를 달성했으므로 여기서 마무리하겠습니다

**Comment by LazoYoung** [comment]
유니티 내장 LOD 기능을 연구해봤는데 LOD Group에 포함된 오브젝트마다 거리를 따로 계산하여 최적화하는 방식이 아닌 것 같아요. LOD Group 컴포넌트가 부착된 GameObject와 카메라뷰 높이의 비율을 바탕으로 거리를 추정하는 식으로 작동하는데, 왼쪽 눈과 오른쪽 눈을 각각 따로 렌더링하는 VR에 대응할 지도 모르겠고, 오브젝트를 그룹핑하는 부모 오브젝트 위치도 재조정할 필요가 있을거라 LOD 방식을 채택하려면 넘어야 할 산이 많습니다.
현재 Culling Group이라고 유니티에서 제공하는 또다른 최적화 도구를 알아보고 있는데, 어떤 방식이 적절한지 비교하고 알려드리겠습니다. @limbj

**Comment by limbj** [comment]
아 그렇군요... 알겠습니다. Culling Group도 한 번 알아봐야겠네요...

**Comment by LazoYoung** [comment]
Resolved in #54
