### ISSUE TITLE
VR 바닷속 잔상이 보이는 현상

### ISSUE THREAD

**Issue by LazoYoung** [LazoYoung/EcoDiver#57]

**Comment by LazoYoung** [comment]
@WooTak123 진행상황 보고 바랍니다

**Comment by WooTak123** [comment]
Crest 공식 Documentation과 구글링을 통해서 알아봤지만 비슷한 사례가 없어서,
버그 원인을 다른 것에서도 추가적으로 찾아봐야할 것 같습니다.

**Comment by LazoYoung** [comment]
https://github.com/wave-harmonic/crest/issues/1130

**Comment by LazoYoung** [comment]
XR Interaction Toolkit 설정에서 렌더링 값을 `Multi-pass` 모드로 변경하면 잔상이 없어집니다.
아마도 Crest 쉐이더가 Single-pass 모드를 지원하지 않는 것 같습니다.
