### ISSUE TITLE
프로그램이 갑자기 종료되는 현상 (D3D11 swapchain)

### ISSUE THREAD

**Issue by LazoYoung** [LazoYoung/EcoDiver#78]
![image](https://github.com/LazoYoung/EcoDiver/assets/9482578/99f44a80-14e2-49ce-ae71-a0ea9750ff86)

간헐적으로 발생하고 있음. 다른 PC 환경에서도 발생하는지 확인 필요

## Possible solutions
- https://forum.unity.com/threads/failed-to-present-d3d11-swapchain-due-to-device-reset-removed-list-of-solutions.1441912/

**Comment by WooTak123** [comment]
GPU가 과부하 상태에 있거나, 시스템이 GPU와의 연결을 잃었을 때 발생하는 것으로 보임.
PC, VR환경 모두 종종 발생. 
화면전환이 빠르게 되거나 이동을 빠르게 할 때 문제인지 확인필요.

**Comment by LazoYoung** [comment]
@WooTak123 Player 설정에서 그래픽 API를 DirectX 12로 바꾸고 테스트해보세요. 증상 해결에 도움이 되는지 확인바랍니다

**Comment by LazoYoung** [comment]
- https://forum.unity.com/threads/constant-crashes-failed-to-present-d3d11-swapchain-due-to-device-removed.987834/page-4#post-8743023
- 완전한 해결책은 아니지만 이렇게 세팅했을 때 크래시 빈도가 줄어들어
- 윈도우11 기준 설정 > 시스템 > 디스플레이 > 그래픽 > 기본 그래픽 설정 변경 > 하드웨어 가속 GPU 스케줄링 Off
- NVIDIA Control Panel > Manage 3D settings > Program Settings > Unity 3D (unity.exe) 2022.3 선택
  - Power management mode = Prefer max performance
  - Threaded optimization = On
  - Triple buffering = Off
  - Vertical sync = Off
  - Apply 적용 후 유니티 재시작

**Comment by LazoYoung** [comment]
TDR 레지스트리 값을 수정하면 크래시가 안뜹니다.
